CREATE PROCEDURE [AFEDive].[GET_DRILL_MEAN_TIME_SUMMARY_FOR_OFFSET_WELLS]
	@API10 VARCHAR(10) 
AS
	SELECT 
		MTS.DEPTH
	   ,(MTS.CUM_WELL_DURATION)/24 as CUM_WELL_DURATION
    FROM [AFEDive].[DRILL_WELL_OFFSET] DWO
    INNER JOIN [AFEDive].[DRILL_OFFSET_MEAN_TIME_SUMMARY] MTS ON MTS.OFFSET_ID = DWO.OFFSET_ID
    WHERE DWO.API10 = @API10
RETURN 0
