CREATE PROCEDURE [AFEDive].[GET_DRILL_VARIANCE_DURATION_BY_API10]
	@api10 varchar(10)
	
AS
	Select API10 , 
			ACTIVITY_PHASE , 
			DEPTH ,
			CUM_PHASE_DURATION ,
			CUM_WELL_DURATION/24 as CUM_WELL_DURATION ,
			ACTIVITY_ID ,
			VARIANCE_AMOUNT , 
			VARIANCE_DURATION_ID,
			ROW_CREATE_DATE,
			VARIANCE_TYPE,
			VARIANCE_COMMENT
		   From [AFEDive].[DRILL_VARIANCE_DURATION]
		   where API10=@api10

	
    
RETURN 0
