CREATE PROCEDURE [AFEDive].[GET_DRILL_TIME_SUMMARY_FOR_OFFSET_WELLS]
	@API10 VARCHAR(10)
AS
	SELECT DTS.[API10]
	,DTS.DEPTH
	,(DTS.CUM_WELL_DURATION)/24 as CUM_WELL_DURATION
	 
 FROM [AFEDive].[DRILL_BEST_OFFSET] DBF
	LEFT JOIN [AFEDive].[DRILL_WELL_OFFSET] DWO ON DWO.OFFSET_ID = DBF.OFFSET_ID
	LEFT JOIN [AFEDive].[DRILL_TIME_SUMMARY] DTS ON (DTS.API10 = DBF.BEST_API10 AND DTS.ACTIVITY_PHASE = DBF.ACTIVITY_PHASE)
WHERE DWO.API10 = @API10 AND DBF.BEST_TYPE = 'DURATION' AND DTS.API10 IS NOT NULL
RETURN 0
