CREATE PROCEDURE [AFEDive].[GET_MEAN_DAILY_COST_FOR_OFFSET_WELLS]
	@API10 VARCHAR(10)
AS
	SELECT MDC.DEPTH, MDC.CUM_WELL_COST
  FROM [AFEDive].[DRILL_WELL_OFFSET] DWO
  INNER JOIN [AFEDive].[DRILL_OFFSET_MEAN_DAILY_COST] MDC ON MDC.OFFSET_ID = MDC.OFFSET_ID
  WHERE DWO.API10 = @API10
RETURN 0
